export const timezoneCities = [
    { city: 'Los Angeles', timezone: 'America/Los_Angeles' },
    { city: 'Denver', timezone: 'America/Denver' },
    { city: 'Chicago', timezone: 'America/Chicago' },
    { city: 'New York', timezone: 'America/New_York' },
    { city: 'Toronto', timezone: 'America/Toronto' },
    { city: 'Mexico City', timezone: 'America/Mexico_City' },
    { city: 'Buenos Aires', timezone: 'America/Argentina/Buenos_Aires' },
    { city: 'São Paulo', timezone: 'America/Sao_Paulo' },
    { city: 'London', timezone: 'Europe/London' },
    { city: 'Paris', timezone: 'Europe/Paris' },
    { city: 'Berlin', timezone: 'Europe/Berlin' },
    { city: 'Madrid', timezone: 'Europe/Madrid' },
    { city: 'Rome', timezone: 'Europe/Rome' },
    { city: 'Istanbul', timezone: 'Europe/Istanbul' },
    { city: 'Moscow', timezone: 'Europe/Moscow' },
    { city: 'Dubai', timezone: 'Asia/Dubai' },
    { city: 'Mumbai', timezone: 'Asia/Kolkata' },
    { city: 'New Delhi', timezone: 'Asia/Kolkata' },
    { city: 'Bangkok', timezone: 'Asia/Bangkok' },
    { city: 'Jakarta', timezone: 'Asia/Jakarta' },
    { city: 'Shanghai', timezone: 'Asia/Shanghai' },
    { city: 'Hong Kong', timezone: 'Asia/Hong_Kong' },
    { city: 'Seoul', timezone: 'Asia/Seoul' },
    { city: 'Tokyo', timezone: 'Asia/Tokyo' },
    { city: 'Sydney', timezone: 'Australia/Sydney' },
    { city: 'Auckland', timezone: 'Pacific/Auckland' },
    { city: 'Cape Town', timezone: 'Africa/Johannesburg' },
    { city: 'Cairo', timezone: 'Africa/Cairo' },
    { city: 'Riyadh', timezone: 'Asia/Riyadh' },
    { city: 'Singapore', timezone: 'Asia/Singapore' },
    { city: 'Kuala Lumpur', timezone: 'Asia/Kuala_Lumpur' },
    { city: 'Lagos', timezone: 'Africa/Lagos' },
    { city: 'Zurich', timezone: 'Europe/Zurich' },
    { city: 'Vienna', timezone: 'Europe/Vienna' },
    { city: 'Amsterdam', timezone: 'Europe/Amsterdam' },
    { city: 'Warsaw', timezone: 'Europe/Warsaw' },
    { city: 'Stockholm', timezone: 'Europe/Stockholm' },
    { city: 'Lisbon', timezone: 'Europe/Lisbon' },
    { city: 'Athens', timezone: 'Europe/Athens' },
    { city: 'Helsinki', timezone: 'Europe/Helsinki' },
    { city: 'Copenhagen', timezone: 'Europe/Copenhagen' },
    { city: 'Brussels', timezone: 'Europe/Brussels' },
  ];
